# @package _global_

models:
  encoder:
    _target_: ${encoder_path}.TimmBackbone
    model_name: 'convnext_tiny.fb_in22k'
    select_features: [0, 1, 2, 3]            # Output layer
    pretrained: true
