defaults:
  - _self_
  - preset:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 42
exp_name: "ocr_training"
project_name: "receipt_ocr_detection"

wandb: True
exp_version: "v2_efficientnet_b3"

resume: null

trainer:
  max_epochs: 20                  # Epoch 증가 (더 긴 학습)
  num_sanity_val_steps: 1
  log_every_n_steps: 50
  check_val_every_n_epoch: 1
  deterministic: True
  accumulate_grad_batches: 4      # Gradient accumulation (effective batch_size = 4 * 4 = 16)
